notifications:
  email: false

matrix:
  include:
    - language: rust
      rust:
        - stable
      jobs:
        allow_failures:
          - rust: nightly
        fast_finish: true
    - language: node_js
      node_js:
        - 'lts/*'
      script:
        - npm install
        - npm test
